name: Build Payload
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install tools
      run: sudo apt-get install -y attr python3
    - name: Build payload
      run: python3 build.py
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: payload
        path: payload.tar.gz
