name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: echo "Hello World"
    - name: check engpc
      run: ls -la engpc || echo "engpc not found"
